# Generated by Django 5.2.4 on 2025-07-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BANKER', 'Banker'), ('CLIENT', 'Client')], max_length=10),
        ),
    ]
